In [26]:
import tensorflow as tf
import numpy as np
from mxnet import nd
import mxnet as mx
import mxnet.gluon as g

In [12]:
tst_shape=(1,2,2,2)

In [13]:
a = np.random.randint(0,6,tst_shape)
b = np.zeros(tst_shape)

In [14]:
a

array([[[[5, 4],
         [0, 4]],

        [[4, 1],
         [4, 3]]]])

___
___
tensorflow中的l2_loss（注意：实际使用时还要在后面除以样本数）

In [16]:
tensor_a=tf.placeholder(dtype='float32',shape=tst_shape,name='a')
tensor_b=tf.placeholder(dtype='float32',shape=tst_shape,name='b')
lss = tf.nn.l2_loss(tensor_a-tensor_b)

In [17]:
sess = tf.InteractiveSession()
sess.run(lss,feed_dict={tensor_a:a,tensor_b:b})

49.5

In [ ]:
a,b真实的l2_loss

In [20]:
np.sum(np.square(a))/2

49.5

___
___
mxnet gluon中的l2_loss

In [28]:
nd_a = nd.array(a)
nd_b = nd.array(b)

In [31]:
criterion=g.loss.L2Loss
criterion(nd_a,nd_b)

L2Loss(batch_axis=
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]
<NDArray 1x2x2x2 @cpu(0)>, w=
[[[[5. 4.]
   [0. 4.]]

  [[4. 1.]
   [4. 3.]]]]
<NDArray 1x2x2x2 @cpu(0)>)

In [32]:
nd_a.shape

(1, 2, 2, 2)